# Generated by Django 4.0.4 on 2022-05-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_cart_remove_cartitem_item_and_more'),
        ('product', '0012_rename_name_comment_user_alter_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
