# Generated by Django 4.0.4 on 2022-05-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220513_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
